# Generated by Django 5.2.4 on 2025-08-07 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couriers', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Nº Pedido')),
                ('observations', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observações')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Aprovado'), ('REFUSED', 'Recusado')], default='PENDING', max_length=20, verbose_name='Status Pagamento')),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Aguardando Coleta'), ('PICKED_UP', 'Coletado'), ('ON_THE_WAY', 'Em Entrega'), ('DELIVERED', 'Entregue'), ('FAILED', 'Não Entregue'), ('RETURNED', 'Devolvido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status Entrega')),
                ('type_order', models.CharField(choices=[('MAIL', 'Correios'), ('DELIVERY', 'MotoBoy')], default='DELIVERY', max_length=20, verbose_name='Tipo de Pedido')),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taxa de Entrega')),
                ('total_amount', models.FloatField(verbose_name='Valor Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='couriers.courier', verbose_name='Entregador')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
