# Generated by Django 5.2.4 on 2025-07-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_status_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado Em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Aguardando coleta'), ('PICKED_UP', 'Coletado pelo motoboy'), ('ON_THE_WAY', 'Em rota de entrega'), ('DELIVERED', 'Entregue ao destinatário'), ('FAILED', 'Entrega não realizada'), ('RETURNED', 'Pedido devolvido ao remetente'), ('CANCELLED', 'Entrega cancelada')], default='PENDING', max_length=20, verbose_name='Status Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado Em'),
        ),
    ]
