# Generated by Django 5.2.4 on 2025-07-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Aguardando Coleta'), ('PICKED_UP', 'Coletado'), ('ON_THE_WAY', 'Em Entrega'), ('DELIVERED', 'Entregue'), ('FAILED', 'Não Entregue'), ('RETURNED', 'Devolvido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Aprovado'), ('REFUSED', 'Recusado')], default='PENDING', max_length=20, verbose_name='Status Pagamento'),
        ),
    ]
