# Generated by Django 5.2.4 on 2025-07-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='observations',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observações'),
        ),
    ]
