# Generated by Django 5.2.4 on 2025-08-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_type_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_order',
            field=models.CharField(choices=[('MAIL', 'Correios'), ('DELIVERY', 'MotoBoy')], default='DELIVERY', max_length=20, verbose_name='Tipo de Pedido'),
        ),
    ]
