# Generated by Django 5.2.4 on 2025-08-03 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
        ('orders', '0007_alter_order_type_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='couriers.courier', verbose_name='Entregador'),
        ),
    ]
