# Generated by Django 5.2.4 on 2025-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Taxa de Entrega'),
            preserve_default=False,
        ),
    ]
