# Generated by Django 5.2.4 on 2025-08-07 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome ou Apelido')),
                ('document', models.CharField(max_length=50, unique=True, verbose_name='Cpf ou Cnpj')),
                ('phone', models.CharField(max_length=50, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('spent_total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Gasto')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(max_length=20, verbose_name='Numero')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Cep')),
                ('state', models.CharField(max_length=20, verbose_name='Estado')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Endereço principal')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
        ),
    ]
