# Generated by Django 5.2.4 on 2025-07-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='spent_total',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Gasto'),
        ),
    ]
