# Generated by Django 5.2.4 on 2025-07-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_address_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default=1, max_length=20, verbose_name='Cep'),
            preserve_default=False,
        ),
    ]
