# Generated by Django 5.2.4 on 2025-07-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_address_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=True, verbose_name='Endereço principal'),
        ),
    ]
