# Generated by Django 5.2.4 on 2025-08-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_address_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default=1, max_length=20, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
