[project]
name = "entregapro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "django-crispy-forms>=2.4",
    "django-widget-tweaks>=1.5.0",
]
