# Generated by Django 5.2.4 on 2025-08-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do motoboy')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
            ],
        ),
    ]
